"""Choose which copy of a duplicate group is kept — deterministically."""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Final

from media_hygiene.constants import KeepReason
from media_hygiene.paths.host_paths import is_within
from media_hygiene.plan.copy_names import looks_like_copy
from media_hygiene.plan.models import KeepDecision
from media_hygiene.plan.name_rules import DEFAULT_NAME_RULES, NameRules

if TYPE_CHECKING:
    from pathlib import Path

    from media_hygiene.scan.models import DuplicateGroup, MediaFile

type _SortKey = tuple[bool, int, bool, bool, bool, bool, int, int, str]

# The reason of each element of the sort key, in the same order.
_CRITERIA: Final = (
    KeepReason.PROTECTED,
    KeepReason.PREFERRED,
    KeepReason.HAS_SIDECAR,
    KeepReason.NOT_A_COPY,
    KeepReason.MEANINGFUL_NAME,
    KeepReason.MEANINGFUL_FOLDER,
    KeepReason.OLDEST,
    KeepReason.SHORTEST_PATH,
    KeepReason.ALPHABETICAL,
)


@dataclass(frozen=True, slots=True)
class KeepPolicy:
    """How to choose the copy to keep.

    Container paths of the preferred (ordered) and protected folders, the names that
    say nothing (generated by a camera or an app, generic folders), and the files
    with a sidecar next to them (their edits).
    """

    preferred: tuple[Path, ...] = ()
    protected: tuple[Path, ...] = ()
    names: NameRules = DEFAULT_NAME_RULES
    with_sidecar: frozenset[Path] = frozenset()

    def is_protected(self, file: MediaFile) -> bool:
        """Tell whether a file lies in a protected folder.

        Args:
            file: Candidate file.

        Returns:
            True when it must never be modified.
        """
        return any(is_within(file.path, folder) for folder in self.protected)

    def rank(self, file: MediaFile) -> _SortKey:
        """Sort key: the smallest key is the copy to keep.

        Order: protected folder, preferred folder (in the configured order), a sidecar
        next to it (its edits), a name that does not look like a copy, a name someone
        chose (not generated by a camera or an app), a folder someone named, the
        oldest modification time, the shortest path, then alphabetical order
        (case-insensitive) as the final tie-breaker. The order follows `KeepReason`.

        Args:
            file: Candidate file.

        Returns:
            Its sort key.
        """
        preference = next(
            (
                index
                for index, folder in enumerate(self.preferred)
                if is_within(file.path, folder)
            ),
            len(self.preferred),
        )
        return (
            not self.is_protected(file),
            preference,
            file.path not in self.with_sidecar,
            looks_like_copy(file.path),
            self.names.has_generated_name(file.path),
            self.names.in_generic_folder(file.path),
            file.mtime_ns,
            len(file.path.parts),
            str(file.path).casefold(),
        )

    def decide(self, group: DuplicateGroup) -> KeepDecision:
        """Split a duplicate group into the keeper, removable and protected copies.

        Args:
            group: Identical files.

        Returns:
            The decision; protected copies other than the keeper are never removable.
        """
        ordered = sorted(group.files, key=self.rank)
        keeper, others = ordered[0], ordered[1:]
        return KeepDecision(
            digest=group.digest,
            size=group.size,
            keeper=keeper,
            removable=tuple(file for file in others if not self.is_protected(file)),
            protected=tuple(file for file in others if self.is_protected(file)),
            reason=self._reason(keeper, others[0]),
        )

    def _reason(self, keeper: MediaFile, runner_up: MediaFile) -> KeepReason:
        """Name the first criterion that ranks the keeper before the next copy.

        Args:
            keeper: The copy kept.
            runner_up: The copy ranked right after it.

        Returns:
            The decisive criterion.
        """
        criteria = zip(self.rank(keeper), self.rank(runner_up), strict=True)
        decisive = next(
            (index for index, (kept, other) in enumerate(criteria) if kept != other),
            len(_CRITERIA) - 1,
        )
        return _CRITERIA[decisive]
