r"""Names that say nothing: generated by a camera or an app, or generic folders.

Between identical copies, the one whose name or folder someone chose
(`Mariage 2015\Marie et Paul.jpg`) is worth more than `DCIM\100CANON\IMG_1234.jpg`:
its name is kept.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import TYPE_CHECKING

from media_hygiene.constants import GENERATED_NAMES, GENERIC_FOLDERS
from media_hygiene.plan.copy_names import without_copy_marks

if TYPE_CHECKING:
    from collections.abc import Iterable
    from pathlib import Path


def compile_patterns(patterns: Iterable[str]) -> tuple[re.Pattern[str], ...]:
    """Compile whole-name, case-insensitive patterns.

    Args:
        patterns: Regular expressions.

    Returns:
        The compiled patterns.

    Raises:
        re.error: A pattern is not a valid regular expression.
    """
    return tuple(re.compile(pattern, re.IGNORECASE) for pattern in patterns)


@dataclass(frozen=True, slots=True)
class NameRules:
    """Recognises generated file names and generic folder names."""

    generated_names: tuple[re.Pattern[str], ...]
    generic_folders: tuple[re.Pattern[str], ...]

    @classmethod
    def from_patterns(cls, names: Iterable[str], folders: Iterable[str]) -> NameRules:
        """Build the rules from regular expressions.

        Args:
            names: Patterns of generated file names (without extension).
            folders: Patterns of generic folder names.

        Returns:
            The rules.
        """
        return cls(compile_patterns(names), compile_patterns(folders))

    def has_generated_name(self, path: Path) -> bool:
        """Tell whether a camera or an app named the file.

        Args:
            path: The file.

        Returns:
            True for names such as `IMG_1234.jpg` or `IMG_1234 (1).jpg`.
        """
        name = without_copy_marks(path.stem)
        return any(pattern.fullmatch(name) for pattern in self.generated_names)

    def in_generic_folder(self, path: Path) -> bool:
        """Tell whether the file sits in a folder named by a device or an app.

        Args:
            path: The file.

        Returns:
            True for folders such as `DCIM`, `100CANON` or `New folder`.
        """
        folder = path.parent.name
        return any(pattern.fullmatch(folder) for pattern in self.generic_folders)


DEFAULT_NAME_RULES = NameRules.from_patterns(GENERATED_NAMES, GENERIC_FOLDERS)
